name: Build Compatibility Tests
on:
  push:
    branches: [ main, audio ]
jobs:
  build-on-ubuntu:
    runs-on: ubuntu-latest
    container:
      image: nvidia/opengl:base
    steps:
      - name: Install git on container
        run: |
          apt update
          apt install -y git

      - name: Checkout Repo
        uses: actions/checkout@v5
        with:
          submodules: 'true'
          # token: ${{ secrets.PAT_TOKEN }}
      - run: chmod +x ./gmake_build.sh
      - run: ./gmake_build.sh clean
