name: Build Compatibility Tests
on:
  push:
    branches: [ main, audio ]
jobs:
  build-on-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: ls
      - name: GMake (GCC) build
        run: ./gmake_build.sh
