name: Build Compatibility Tests
on:
  push:
    branches: [ main, audio ]
jobs:
  build-on-windows:
    runs-on: windows-latest
    steps:
      - name: Setup
        uses: microsoft/setup-msbuild@v2

      - name: Checkout Repo
        uses: actions/checkout@v5
        with:
          submodules: 'true'
          # token: ${{ secrets.PAT_TOKEN }}

      - name: Test
        run: |
          ./vs_build.bat
          more TankEngine.sln
          msbuild TankEditor.vcxproj /p:Platform=x64
          msbuild TankPlayer.vcxproj /p:Platform=x64

  build-on-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5
        with:
          submodules: 'true'
          # token: ${{ secrets.PAT_TOKEN }}

      - name: Setup
        run: |
          sudo apt update
          xargs sudo apt install -y < apt-packages.txt
      
      - name: Test
        run: |
          chmod +x ./gmake_build.sh
          ./gmake_build.sh clean